### ISSUE TITLE
alpha2.1 set_ver_length

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/ioPlacer#11]
Hello, 

`set_ver_length` calls `setHorizontalLength`. See:
https://github.com/The-OpenROAD-Project/ioPlacer/blob/7191553002f8884d7eeac9595e036d382d7dcb6c/src/TclInterface.cpp#L139

Thank you

**Comment by rovinski** [comment]
@mpfogaca this should be a straightforward fix. Can you update the alpha2.1 branch and cherry-pick to the other branches? Both `set_ver_length` and `get_ver_length` need to be updated.

**Comment by mpfogaca** [comment]
Hi @kareefardi and @rovinski,

I've filed a pull request. I hope this issue will be in alpha2.1 branch soon.

Thanks,
--Mateus

**Comment by mpfogaca** [comment]
Hi, @kareefardi and @rovinski.

The fix is commited to Alpha2.1 branch. 

Thanks,
--Mateus
