### ISSUE TITLE
Incompatible files for ppc64le

### ISSUE THREAD

**Issue by iam41xin** [The-OpenROAD-Project/ioPlacer#3]
Hello guys,

I’ve compiled and ran this whole project under x86_64 before, it was successful, it’s a very nice project for IC designers like me, thank you very much!

Now I’m trying to compile these components under ppc64le, some of them were successfully completed, like cts, yosys, router. 

For ioPlacer, there is a little problem for me.

It seems like there’re two files maybe pre-compiled for x86_64, not compatible with ppc64le. 

A part of detail information is pasted here, please have a look that if it’s possible to provide ppc64le suitable files. Thanks again!

[ 50%] Building CXX object CMakeFiles/ioPlacer.dir/src/IOPlacementKernel.cpp.o
[ 57%] Building CXX object CMakeFiles/ioPlacer.dir/src/LEFParser.cpp.o
[ 64%] Building CXX object CMakeFiles/ioPlacer.dir/src/Main.cpp.o
[ 71%] Building CXX object CMakeFiles/ioPlacer.dir/src/Netlist.cpp.o
[ 78%] Building CXX object CMakeFiles/ioPlacer.dir/src/Parameters.cpp.o
[ 85%] Building CXX object CMakeFiles/ioPlacer.dir/src/Parser.cpp.o
[ 92%] Building CXX object CMakeFiles/ioPlacer.dir/src/WriterIOPins.cpp.o
[100%] Linking CXX executable ioPlacer
/opt/rh/devtoolset-7/root/usr/libexec/gcc/ppc64le-redhat-linux/7/ld: skipping incompatible /ioPlacer/lib/libdef.a when searching for -ldef
/opt/rh/devtoolset-7/root/usr/libexec/gcc/ppc64le-redhat-linux/7/ld: cannot find -ldef
/opt/rh/devtoolset-7/root/usr/libexec/gcc/ppc64le-redhat-linux/7/ld: skipping incompatible /ioPlacer/lib/liblef.a when searching for -llef
/opt/rh/devtoolset-7/root/usr/libexec/gcc/ppc64le-redhat-linux/7/ld: cannot find -llef
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ioPlacer.dir/build.make:410: ioPlacer] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/ioPlacer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
The command '/bin/sh -c cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/opt/rh/rh-mongodb36/root/usr ..  &&     make' returned a non-zero code: 2

**Comment by vvbandeira** [comment]
LEF/DEF were added as submodules, this should fix build issues. can you check? Thanks.

**Comment by iam41xin** [comment]
> LEF/DEF were added as submodules, this should fix build issues. can you check and close the issue? Thanks.

YES!!! It's very nice of you. I've completed to compile these static libraries, both ioplacer and fastroute work fine under ppc64le now.
Also I think it would be very nice to modify the Dockerfiles, from 'git clone' to 'git clone --recursive'.
^_^

**Comment by tajayi** [comment]
The docker file at https://github.com/The-OpenROAD-Project/alpha-release/blob/master/build/docker/ioplacer/Dockerfile has been updated.

Thanks
