### ISSUE TITLE
ioPlacer handling high pin count designs

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/ioPlacer#5]
We have experienced issues with ioPlacer handling designs with very high pin count. It is possible that these designs have more pins than can be spread across the block the horizontal and vertical layer specified. I have observed a few designs where ioPlacer fails to sensibly place the IOs but doesn't error out, causing issues for downstream tools.

The request is to
1. Print a user-readable error when the ioPlacement is not performed well (perhaps because there is not anough perimiter to spread the pins) and throw an error code on exit.
2. Add support for spreading across multiple layers. e.g with the arguements `-h "3 5" -v "4 6"`

**Comment by vvbandeira** [comment]
Hi @tajayi, 

Regarding (1): commit `ee52bdd` adds a check if all pins can be placed (this commit is merged into the master branch). If you can either test the new version or provide a minimal testcase where this problem occurs, we can further investigate and test our tool.

(PS. There is an open problem with some designs having pins placed in the def file but not read/considered by commercial tools. We will update when we have a better grasp/a fix for this)

Regarding (2): we believe that this is an interesting enhancement that can be added in the near future, but right now, we will focus our effort towards a stable tool and tests. If the problem regarding designs with high pin count is `closed` please open a new issue requesting the feature in (2).

Thanks,

**Comment by mpfogaca** [comment]
Hi, @tajayi.

Should we resume this thread or drop it?

Thanks,
--Mateus

**Comment by tajayi** [comment]
We can drop it for now. It's not impeding anything I can see
